apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: obsctl-reloader
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app.kubernetes.io/component: obsctl-reloader
      app.kubernetes.io/instance: obsctl-reloader
      app.kubernetes.io/name: obsctl-reloader
      app.kubernetes.io/version: latest
    name: obsctl-reloader
    namespace: observatorium-stage
  spec:
    replicas: ${REPLICAS}
    selector:
      matchLabels:
        app.kubernetes.io/component: obsctl-reloader
        app.kubernetes.io/instance: obsctl-reloader
        app.kubernetes.io/name: obsctl-reloader
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
    template:
      metadata:
        labels:
          app.kubernetes.io/component: obsctl-reloader
          app.kubernetes.io/instance: obsctl-reloader
          app.kubernetes.io/name: obsctl-reloader
          app.kubernetes.io/version: latest
      spec:
        containers:
        - args:
          - --log.level=info
          - --web.internal.listen=0.0.0.0:8081
          - --sleep-duration-seconds=${SLEEP_DURATION_SECONDS}
          - --config-reload-interval-seconds=${CONFIG_RELOAD_INTERVAL_SECONDS}
          - --observatorium-api-url=${OBSERVATORIUM_URL}
          - --managed-tenants=${MANAGED_TENANTS}
          - --issuer-url=${OIDC_ISSUER_URL}
          - --audience=${OIDC_AUDIENCE}
          - --log-rules-enabled=true
          env:
          - name: NAMESPACE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          name: obsctl-reloader
          resources: {}
        serviceAccountName: obsctl-reloader
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      app.kubernetes.io/component: obsctl-reloader
      app.kubernetes.io/instance: obsctl-reloader
      app.kubernetes.io/name: obsctl-reloader
      app.kubernetes.io/version: latest
    name: obsctl-reloader
    namespace: observatorium-stage
  rules:
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - prometheusrules
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - loki.grafana.com
    resources:
    - alertingrules
    - recordingrules
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      app.kubernetes.io/component: obsctl-reloader
      app.kubernetes.io/instance: obsctl-reloader
      app.kubernetes.io/name: obsctl-reloader
      app.kubernetes.io/version: latest
    name: obsctl-reloader
    namespace: observatorium-stage
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: obsctl-reloader
  subjects:
  - kind: ServiceAccount
    name: obsctl-reloader
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/component: obsctl-reloader
      app.kubernetes.io/instance: obsctl-reloader
      app.kubernetes.io/name: obsctl-reloader
      app.kubernetes.io/version: latest
    name: obsctl-reloader
    namespace: observatorium-stage
  spec:
    ports:
    - name: internal
      port: 8081
      targetPort: 8081
    selector:
      app.kubernetes.io/component: obsctl-reloader
      app.kubernetes.io/instance: obsctl-reloader
      app.kubernetes.io/name: obsctl-reloader
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/component: obsctl-reloader
      app.kubernetes.io/instance: obsctl-reloader
      app.kubernetes.io/name: obsctl-reloader
      app.kubernetes.io/version: latest
    name: obsctl-reloader
    namespace: observatorium-stage
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: obsctl-reloader
    namespace: observatorium-stage
  spec:
    endpoints:
    - port: internal
    selector:
      matchLabels:
        app.kubernetes.io/component: obsctl-reloader
        app.kubernetes.io/instance: obsctl-reloader
        app.kubernetes.io/name: obsctl-reloader
        app.kubernetes.io/version: latest
parameters:
- name: IMAGE
  value: quay.io/app-sre/obsctl-reloader
- name: IMAGE_TAG
  value: latest
- name: OBSERVATORIUM_URL
  value: https://observatorium.api.stage.openshift.com
- name: OIDC_AUDIENCE
  value: observatorium
- name: OIDC_ISSUER_URL
  value: https://sso.redhat.com/auth/realms/redhat-external
- name: RHOBS_SECRET_NAME
  value: rhobs-tenant-staging
- name: SLEEP_DURATION_SECONDS
  value: 30
- name: CONFIG_RELOAD_INTERVAL_SECONDS
  value: 60
- name: MANAGED_TENANTS
  value: rhobs
- name: REPLICAS
  value: "1"
